name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub Actions runner, not the Amazon Linux instance

    if: github.ref == 'refs/heads/main'

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies and build
        run: |
          npm install
          npm run install-frontend
          npm run install-backend
          npm run build

      - name: Stop existing PM2 process (if any) on Amazon Linux
        run: |
          ssh -i "${{ secrets.SSH_PRIVATE_KEY }}" -o StrictHostKeyChecking=no ec2-user@3.127.230.197 "pm2 stop index || true"


      - name: Deploy to Amazon Linux using rsync
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./*
          remote_path: /home/ec2-user/agency
          remote_host: 3.127.230.197
          remote_user: ec2-user
          remote_key: "${{ secrets.SSH_PRIVATE_KEY }}"

      - name: Start PM2 process on Amazon Linux
        run: |
          ssh -i "${{ secrets.SSH_PRIVATE_KEY }}" -o StrictHostKeyChecking=no ec2-user@3.127.230.197 "pm2 start index || true"
